indent-width = 4
line-length = 99
target-version = "py39"

[lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes + flake8
    "I",  # isort
    "UP", # pyupgrade
    "W",  # pycodestyle
]
ignore = [
    "UP031",  # Use format specifiers instead of percent format; TODO drop
]
