# This file is part of git-big-picture
#
# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
#
# git-big-picture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# git-big-picture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with git-big-picture.  If not, see <http://www.gnu.org/licenses/>.

name: Tests

# Drop permissions to minimum for security
permissions:
  contents: read

on:
- pull_request
- push

jobs:
  run-tests:
    name: Tests
    strategy:
      matrix:
        python-version: ["3.10", 3.14]  # oldest and most recent version supported
        runs-on: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install --no-install-recommends -y graphviz
    - name: Install build dependencies (macOS only)
      if: runner.os == 'macOS'
      run: |
        brew install graphviz
    - name: Run the test suite
      run: |
        ./run-tests-with-coverage.sh
